### PR TITLE
v0.3.13.0

### PR DESCRIPTION
**Pull request by mfansler**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Upstream has a dependency on `pandoc-types`, but I don't find this on Conda Forge - do we need a new feedstock for this?

### CODE REVIEW

**Comment by mfansler** [comment]
@conda-forge-admin, please rerender

**Comment by mfansler** [comment]
All is passing, but please comment on `pandoc-types` before merging (not my expertise):

> Upstream has a dependency on pandoc-types, but I don't find this on Conda Forge - do we need a new feedstock for this?

**Comment by mfhepp** [comment]
Maybe @jgm or @tarleb could help clarify this and remove this blocker? My purely gut feeling is that the dependency is not needed for pandoc-crossref and provided by pandoc itself. But it would be good to get this out of the way.

**Review by knaaptime — APPROVED** [review]

**Comment by tarleb** [comment]
I'd be happy to help, but not sure if I understand the issue. Is the question if pandoc-crossref should depend on pandoc-types?

Maybe this info helps: pandoc-crossref depends on pandoc-the-library, not pandoc-the-executable. Because of that it has a transitive dependency on pandoc-types on build-time. Does that help?

**Comment by mfhepp** [comment]
Thanks, @tarleb for this info! I do not really understand the mechanics of conda feedstocks, but if I get it right, then this feedstock links to the release builds explicitly. 

As @knaaptime also reviewed and approved of this pull-request, I would recommend going forward and merge the PR.

**Comment by mfansler** [comment]
@tarleb yes, that helps. We can omit it from the recipe definition because we redistribute the executable from upstream.

@mfhepp thanks for helping move this forward!

**Comment by mfhepp** [comment]
You are very welcome!

**Pull request merged**
