### PR TITLE
Release 0.3.11.0

### PR DESCRIPTION
**Pull request by LaurentRDC**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ickc** [comment]
Is there any reason to remove postf1 and postf2?

**Comment by LaurentRDC** [comment]
I didn't understand why "postf1" and "postf2" were separate, but most importantly the usage of these variables can be folded in with the "version" variable. Isn't it simpler to use e.g. ```{% set version = "0.3.11.0x" %}``` instead? 

I understand that this is subjective, so I'm happy to revert this particular change if you want

**Comment by ickc** [comment]
I don't understand it either, especially it is not documented. It would be helpful if whoever first defined them to explain them (and documenting it directly inside meta.yaml would be helpful.)

However, if you look at the commit history, in the beginning it wasn't like that, and the conventions changed from time to time. It seems like they have experimented with different ways and found that this is better.

From the code itself, it is obviously that postf1 only affects version, and postf2 only affects the url. e.g. for 0.3.10.0a, they don't want the version to show the "a", and yet it is in the url. See <https://github.com/lierdakil/pandoc-crossref/issues/311#issuecomment-844626176> for the meaning of "a" there.

**Comment by LaurentRDC** [comment]
Ok let's go back to the previous versioning scheme for now

**Comment by ickc** [comment]
Some additional commits are added in #43.

**Pull request closed without merging**
